# Generated by Django 2.2 on 2022-07-29 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0002_profilefeeditem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilefeeditem',
            old_name='status_tex',
            new_name='status_text',
        ),
    ]
